version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    # Group updates to reduce PR noise
    groups:
      next-js:
        patterns:
          - 'next*'
          - '@next/*'
      react:
        patterns:
          - 'react*'
          - '@types/react*'
      testing:
        patterns:
          - 'vitest*'
          - '@testing-library/*'
          - '@types/jest*'
      linting:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
          - 'prettier*'
      ui:
        patterns:
          - '@radix-ui/*'
          - 'tailwindcss*'
          - 'lucide-react*'
    # Limit open PRs
    open-pull-requests-limit: 5
    # Allow all dependency types
    allow:
      - dependency-type: 'direct'
      - dependency-type: 'indirect'
    # Commit message preferences
    commit-message:
      prefix: 'chore'
      include: 'scope'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'ci'
