import type { CoursePlannerPreset } from '../types';

const G = {
  comm: 'Foundation — Communication Skills',
  cs: 'Foundation — Computer Skills',
  num: 'Foundation — Numeracy',
  nat: 'Foundation — Natural Sciences',
  soc: 'Foundation — Social Sciences',
  hum: 'Foundation — Humanities',
  lfe: 'Foundation — Live-In-Field Experience',
  core: 'Core',
  proj: 'Major Projects',
  a01: 'Area 01 — Software Engineering',
  a02: 'Area 02 — Data Communication & Networking',
  a03: 'Area 03 — Digital System Design',
  a04: 'Area 04 — Data Science',
  a05: 'Area 05 — Intelligent Systems',
  a06a: 'Area 06A — Information Systems & Processing',
  a06b: 'Area 06B — Information Systems & Processing',
  a07: 'Area 07 — CS Theory',
  a08: 'Area 08 — Scientific Computing',
  a09: 'Area 09 — Data Analytics & Digitalization',
  a10: 'Area 10 — Information Technology',
  special: 'Special Topics',
} as const;

export const IUB_CSE_PRESET: CoursePlannerPreset = {
  name: 'IUB — BSc CSE (Curriculum 01, Spring 2024)',
  courses: [
    // ── Foundation — Communication Skills ───────────────────────────────
    {
      id: 'eng101',
      code: 'ENG 101',
      title: 'English Listening and Speaking Skills',
      credits: 3,
      prerequisites: [],
      group: G.comm,
    },
    {
      id: 'eng102',
      code: 'ENG 102',
      title: 'English Reading Skills',
      credits: 3,
      prerequisites: [],
      group: G.comm,
    },
    {
      id: 'eng107',
      code: 'ENG 107',
      title: 'Professional Writing',
      credits: 3,
      prerequisites: ['eng101', 'eng102'],
      group: G.comm,
    },

    // ── Foundation — Computer Skills ────────────────────────────────────
    {
      id: 'cse100',
      code: 'CSE 100',
      title: 'Computer Programming I',
      credits: 3,
      prerequisites: [],
      group: G.cs,
    },
    {
      id: 'cse100l',
      code: 'CSE 100L',
      title: 'Labwork for CSE 100',
      credits: 1,
      prerequisites: [],
      group: G.cs,
    },

    // ── Foundation — Numeracy ────────────────────────────────────────────
    {
      id: 'mat104',
      code: 'MAT 104',
      title: 'Calculus and Analytical Geometry',
      credits: 3,
      prerequisites: [],
      group: G.num,
    },
    {
      id: 'mat212',
      code: 'MAT 212',
      title: 'Probability & Statistics for Sc & Engg',
      credits: 3,
      prerequisites: ['mat104'],
      group: G.num,
    },

    // ── Foundation — Natural Sciences ─────────────────────────────────
    {
      id: 'phy101',
      code: 'PHY 101',
      title: 'University Physics I',
      credits: 3,
      prerequisites: [],
      group: G.nat,
    },
    {
      id: 'phy101l',
      code: 'PHY 101L',
      title: 'University Physics I Lab',
      credits: 1,
      prerequisites: [],
      group: G.nat,
    },
    {
      id: 'phy102',
      code: 'PHY 102',
      title: 'University Physics II',
      credits: 3,
      prerequisites: ['phy101'],
      group: G.nat,
    },
    {
      id: 'phy102l',
      code: 'PHY 102L',
      title: 'University Physics II Lab',
      credits: 1,
      prerequisites: ['phy101l'],
      group: G.nat,
    },

    // ── Foundation — Social Sciences ──────────────────────────────────
    {
      id: 'ant101',
      code: 'ANT 101',
      title: 'Introduction to Anthropology',
      credits: 3,
      prerequisites: [],
      group: G.soc,
    },
    {
      id: 'cmn201',
      code: 'CMN 201',
      title: 'Introduction to Communication',
      credits: 3,
      prerequisites: [],
      group: G.soc,
    },
    {
      id: 'ecn200',
      code: 'ECN 200',
      title: 'Introduction to Economics',
      credits: 3,
      prerequisites: [],
      group: G.soc,
    },
    {
      id: 'soc101',
      code: 'SOC 101',
      title: 'Introductory Sociology',
      credits: 3,
      prerequisites: [],
      group: G.soc,
    },
    {
      id: 'hea101',
      code: 'HEA 101',
      title: 'Health and Society',
      credits: 3,
      prerequisites: [],
      group: G.soc,
    },
    {
      id: 'soc202',
      code: 'SOC 202',
      title: 'Social Psychology',
      credits: 3,
      prerequisites: [],
      group: G.soc,
    },
    {
      id: 'soc301',
      code: 'SOC 301',
      title: 'Social Science Research Methodology',
      credits: 3,
      prerequisites: [],
      group: G.soc,
    },

    // ── Foundation — Humanities ───────────────────────────────────────
    {
      id: 'bla101',
      code: 'BLA 101',
      title: 'Bangla Literature and Art',
      credits: 3,
      prerequisites: [],
      group: G.hum,
    },
    {
      id: 'bds109',
      code: 'BDS 109',
      title: 'Bangladesh 1971 Through the Lenses',
      credits: 3,
      prerequisites: [],
      group: G.hum,
    },
    {
      id: 'bng201',
      code: 'BNG 201',
      title: 'Bangla Literature',
      credits: 3,
      prerequisites: [],
      group: G.hum,
    },
    {
      id: 'bph101',
      code: 'BPH 101',
      title: 'Bangladesh Political History',
      credits: 3,
      prerequisites: [],
      group: G.hum,
    },
    {
      id: 'nch101',
      code: 'NCH 101',
      title: 'National Culture & Heritage I',
      credits: 3,
      prerequisites: [],
      group: G.hum,
    },

    // ── Foundation — Live-In-Field Experience ─────────────────────────
    {
      id: 'lfe201',
      code: 'LFE 201',
      title: 'Live-in-Field Experience',
      credits: 3,
      prerequisites: [],
      group: G.lfe,
    },

    // ── Core ──────────────────────────────────────────────────────────
    {
      id: 'cse104',
      code: 'CSE 104',
      title: 'Electrical Circuit Analysis',
      credits: 3,
      prerequisites: ['phy101'],
      group: G.core,
    },
    {
      id: 'cse104l',
      code: 'CSE 104L',
      title: 'Electrical Circuit Analysis Lab',
      credits: 1,
      prerequisites: ['phy101l'],
      group: G.core,
    },
    {
      id: 'cse200',
      code: 'CSE 200',
      title: 'Computer Programming II',
      credits: 3,
      prerequisites: ['cse100', 'cse100l'],
      group: G.core,
    },
    {
      id: 'cse200l',
      code: 'CSE 200L',
      title: 'Labwork for CSE 200',
      credits: 1,
      prerequisites: ['cse100', 'cse100l'],
      group: G.core,
    },
    {
      id: 'cse201',
      code: 'CSE 201',
      title: 'Discrete Mathematics',
      credits: 3,
      prerequisites: ['cse100', 'cse100l'],
      group: G.core,
    },
    {
      id: 'cse203',
      code: 'CSE 203',
      title: 'Data Structure',
      credits: 3,
      prerequisites: ['cse100', 'cse100l', 'cse200', 'cse200l'],
      group: G.core,
    },
    {
      id: 'cse203l',
      code: 'CSE 203L',
      title: 'Data Structure Lab',
      credits: 1,
      prerequisites: ['cse100', 'cse100l', 'cse200', 'cse200l'],
      group: G.core,
    },
    {
      id: 'cse204',
      code: 'CSE 204',
      title: 'Digital Logic Design',
      credits: 3,
      prerequisites: ['cse100', 'cse100l', 'cse200', 'cse200l'],
      group: G.core,
    },
    {
      id: 'cse204l',
      code: 'CSE 204L',
      title: 'Digital Logic Design Lab',
      credits: 1,
      prerequisites: ['cse100', 'cse100l', 'cse200', 'cse200l'],
      group: G.core,
    },
    {
      id: 'cse210',
      code: 'CSE 210',
      title: 'Electronics I',
      credits: 3,
      prerequisites: ['cse104', 'cse104l'],
      group: G.core,
    },
    {
      id: 'cse210l',
      code: 'CSE 210L',
      title: 'Labwork based on CSE 210',
      credits: 1,
      prerequisites: ['cse104', 'cse104l'],
      group: G.core,
    },
    {
      id: 'cse211',
      code: 'CSE 211',
      title: 'Algorithms',
      credits: 3,
      prerequisites: ['cse203', 'cse203l'],
      group: G.core,
    },
    {
      id: 'cse211l',
      code: 'CSE 211L',
      title: 'Labwork based on CSE 211',
      credits: 1,
      prerequisites: ['cse203', 'cse203l'],
      group: G.core,
    },
    {
      id: 'cse213',
      code: 'CSE 213',
      title: 'Object Oriented Programming',
      credits: 3,
      prerequisites: ['cse211', 'cse211l'],
      group: G.core,
    },
    {
      id: 'cse213l',
      code: 'CSE 213L',
      title: 'Labwork based on CSE 213',
      credits: 1,
      prerequisites: ['cse211', 'cse211l'],
      group: G.core,
    },
    {
      id: 'cse214',
      code: 'CSE 214',
      title: 'Computer Organization and Architecture',
      credits: 3,
      prerequisites: ['cse204', 'cse204l'],
      group: G.core,
    },
    {
      id: 'cse216',
      code: 'CSE 216',
      title: 'Microprocessor, Interfacing and Assembly Language',
      credits: 3,
      prerequisites: ['cse204', 'cse204l'],
      group: G.core,
    },
    {
      id: 'cse216l',
      code: 'CSE 216L',
      title: 'Labwork based on CSE 216',
      credits: 1,
      prerequisites: ['cse204', 'cse204l'],
      group: G.core,
    },
    {
      id: 'mat203',
      code: 'MAT 203',
      title: 'Linear Algebra - Vectors and Matrices',
      credits: 3,
      prerequisites: ['cse213', 'cse213l'],
      group: G.core,
    },
    {
      id: 'mat251',
      code: 'MAT 251',
      title: 'Multivariable Calculus',
      credits: 3,
      prerequisites: ['mat104', 'mat203'],
      group: G.core,
    },
    {
      id: 'cse303',
      code: 'CSE 303',
      title: 'Database Management',
      credits: 3,
      prerequisites: ['cse213', 'cse213l'],
      group: G.core,
    },
    {
      id: 'cse303l',
      code: 'CSE 303L',
      title: 'Labwork based on CSE 303',
      credits: 1,
      prerequisites: ['cse213', 'cse213l'],
      group: G.core,
    },
    {
      id: 'cse309',
      code: 'CSE 309',
      title: 'Web Programming',
      credits: 3,
      prerequisites: ['cse303', 'cse303l'],
      group: G.core,
    },
    {
      id: 'cse310',
      code: 'CSE 310',
      title: 'Electronics II',
      credits: 3,
      prerequisites: ['cse210', 'cse210l'],
      group: G.core,
    },
    {
      id: 'cse310l',
      code: 'CSE 310L',
      title: 'Labwork based on CSE 310',
      credits: 1,
      prerequisites: ['cse210', 'cse210l'],
      group: G.core,
    },
    {
      id: 'cse315',
      code: 'CSE 315',
      title: 'Design of Operating System',
      credits: 3,
      prerequisites: ['cse214'],
      group: G.core,
    },
    {
      id: 'cse316',
      code: 'CSE 316',
      title: 'Computer Networks',
      credits: 3,
      prerequisites: ['cse216', 'cse216l'],
      group: G.core,
    },
    {
      id: 'cse316l',
      code: 'CSE 316L',
      title: 'Labwork based on CSE 316',
      credits: 3,
      prerequisites: ['cse216', 'cse216l'],
      group: G.core,
    },
    {
      id: 'cse317',
      code: 'CSE 317',
      title: 'Numerical Methods',
      credits: 3,
      prerequisites: ['cse211', 'cse211l', 'mat212', 'mat251'],
      group: G.core,
    },
    {
      id: 'cse317l',
      code: 'CSE 317L',
      title: 'Labwork based on CSE 317',
      credits: 1,
      prerequisites: ['cse317'],
      group: G.core,
    },
    {
      id: 'cse425',
      code: 'CSE 425',
      title: 'Artificial Intelligence',
      credits: 3,
      prerequisites: ['cse317'],
      group: G.core,
    },
    {
      id: 'cse451',
      code: 'CSE 451',
      title: 'Software Engineering',
      credits: 3,
      prerequisites: ['cse303', 'cse303l'],
      group: G.core,
    },
    {
      id: 'cse451l',
      code: 'CSE 451L',
      title: 'Labwork on CSE 451',
      credits: 1,
      prerequisites: ['cse303', 'cse303l'],
      group: G.core,
    },

    // ── Major Projects ────────────────────────────────────────────────
    {
      id: 'cse298',
      code: 'CSE 298',
      title: '2nd Year Project',
      credits: 2,
      prerequisites: ['cse216', 'cse216l'],
      group: G.proj,
    },
    {
      id: 'cse398',
      code: 'CSE 398',
      title: '3rd Year Project',
      credits: 2,
      prerequisites: ['cse298', 'cse451', 'cse451l'],
      group: G.proj,
    },
    {
      id: 'cse498',
      code: 'CSE 498',
      title: 'Senior Project',
      credits: 6,
      prerequisites: ['cse398', 'cse425'],
      group: G.proj,
    },

    // ── Area 01 — Software Engineering ───────────────────────────────
    {
      id: 'cse307',
      code: 'CSE 307',
      title: 'System Analysis and Design',
      credits: 3,
      prerequisites: ['cse451', 'cse451l'],
      group: G.a01,
    },
    {
      id: 'cse452',
      code: 'CSE 452',
      title: 'Software Marketing',
      credits: 3,
      prerequisites: ['cse451', 'cse451l'],
      group: G.a01,
    },
    {
      id: 'cse453',
      code: 'CSE 453',
      title: 'Software Requirement Engineering',
      credits: 3,
      prerequisites: ['cse451', 'cse451l'],
      group: G.a01,
    },
    {
      id: 'cse454',
      code: 'CSE 454',
      title: 'Software Engineering Process Management',
      credits: 3,
      prerequisites: ['cse451', 'cse451l'],
      group: G.a01,
    },
    {
      id: 'cse456',
      code: 'CSE 456',
      title: 'Business Process Reengineering',
      credits: 3,
      prerequisites: ['cse451', 'cse451l'],
      group: G.a01,
    },
    {
      id: 'cse458',
      code: 'CSE 458',
      title: 'Software Quality and Testing',
      credits: 3,
      prerequisites: ['cse451', 'cse451l'],
      group: G.a01,
    },
    {
      id: 'cse459',
      code: 'CSE 459',
      title: 'Software Architecture and Component-Based Design',
      credits: 3,
      prerequisites: ['cse451', 'cse451l'],
      group: G.a01,
    },
    {
      id: 'cse461',
      code: 'CSE 461',
      title: 'Advance Topics for Application Development',
      credits: 3,
      prerequisites: ['cse309'],
      group: G.a01,
    },
    {
      id: 'cse462',
      code: 'CSE 462',
      title: 'Entrepreneurship Development',
      credits: 3,
      prerequisites: ['cse307', 'cse309'],
      group: G.a01,
    },
    {
      id: 'bus202',
      code: 'BUS 202',
      title: 'Business',
      credits: 3,
      prerequisites: [],
      group: G.a01,
    },
    {
      id: 'mgt481',
      code: 'MGT 481',
      title: 'Project Management',
      credits: 3,
      prerequisites: ['bus202'],
      group: G.a01,
    },

    // ── Area 02 — Data Communication & Networking ─────────────────────
    {
      id: 'cse400',
      code: 'CSE 400',
      title: 'Data Communication',
      credits: 3,
      prerequisites: ['cse316', 'cse316l'],
      group: G.a02,
    },
    {
      id: 'cse401',
      code: 'CSE 401',
      title: 'Signals & Systems',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a02,
    },
    {
      id: 'cse402',
      code: 'CSE 402',
      title: 'Wireless Networking & Mobile Communication',
      credits: 3,
      prerequisites: ['cse400'],
      group: G.a02,
    },
    {
      id: 'cse403',
      code: 'CSE 403',
      title: 'Network Management',
      credits: 3,
      prerequisites: ['cse400'],
      group: G.a02,
    },
    {
      id: 'cse406',
      code: 'CSE 406',
      title: 'Cryptography and Network Security',
      credits: 3,
      prerequisites: ['cse316', 'cse316l'],
      group: G.a02,
    },
    {
      id: 'cse407',
      code: 'CSE 407',
      title: 'Telecommunication Engineering',
      credits: 3,
      prerequisites: ['cse400'],
      group: G.a02,
    },
    {
      id: 'cse408',
      code: 'CSE 408',
      title: 'Advanced Computer Network',
      credits: 3,
      prerequisites: ['cse316', 'cse316l'],
      group: G.a02,
    },
    {
      id: 'cse409',
      code: 'CSE 409',
      title: 'Optical Fiber Communication',
      credits: 3,
      prerequisites: ['cse400'],
      group: G.a02,
    },
    {
      id: 'cse415',
      code: 'CSE 415',
      title: 'Real-time Multimedia Communication',
      credits: 3,
      prerequisites: ['cse400'],
      group: G.a02,
    },
    {
      id: 'cse443',
      code: 'CSE 443',
      title: 'Digital Signal Processing',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a02,
    },

    // ── Area 03 — Digital System Design ──────────────────────────────
    {
      id: 'cse441',
      code: 'CSE 441',
      title: 'Instrumentation & Measurements',
      credits: 3,
      prerequisites: ['cse216', 'cse216l'],
      group: G.a03,
    },
    {
      id: 'cse442',
      code: 'CSE 442',
      title: 'Embedded Systems',
      credits: 3,
      prerequisites: ['cse216', 'cse216l'],
      group: G.a03,
    },
    {
      id: 'cse444',
      code: 'CSE 444',
      title: 'Digital Electronics and Pulse Techniques',
      credits: 3,
      prerequisites: ['cse310', 'cse310l'],
      group: G.a03,
    },
    {
      id: 'cse446',
      code: 'CSE 446',
      title: 'Digital System Design',
      credits: 3,
      prerequisites: ['cse214'],
      group: G.a03,
    },
    {
      id: 'cse447',
      code: 'CSE 447',
      title: 'Computer Peripherals & Interfacing',
      credits: 3,
      prerequisites: ['cse216', 'cse216l'],
      group: G.a03,
    },
    {
      id: 'cse448',
      code: 'CSE 448',
      title: 'VLSI Design & Testing',
      credits: 3,
      prerequisites: ['cse310', 'cse310l'],
      group: G.a03,
    },
    {
      id: 'cse445',
      code: 'CSE 445',
      title: 'Introduction to Nanotechnology',
      credits: 3,
      prerequisites: ['cse310', 'cse310l'],
      group: G.a03,
    },
    {
      id: 'cse449',
      code: 'CSE 449',
      title: 'Fault Tolerant System',
      credits: 3,
      prerequisites: ['cse446'],
      group: G.a03,
    },

    // ── Area 04 — Data Science ────────────────────────────────────────
    {
      id: 'cse410',
      code: 'CSE 410',
      title: 'Mathematical and Statistical Methods for Data Analysis',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a04,
    },
    {
      id: 'cse417',
      code: 'CSE 417',
      title: 'Data Mining and Warehouse',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a04,
    },
    {
      id: 'cse421',
      code: 'CSE 421',
      title: 'Machine Learning',
      credits: 3,
      prerequisites: ['cse425'],
      group: G.a04,
    },
    {
      id: 'cse432',
      code: 'CSE 432',
      title: 'Introduction to Data Science',
      credits: 3,
      prerequisites: ['cse317', 'cse317l', 'cse303', 'cse303l'],
      group: G.a04,
    },
    {
      id: 'cse438',
      code: 'CSE 438',
      title: 'Algorithms for Mining Massive Datasets',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a04,
    },
    {
      id: 'cse472',
      code: 'CSE 472',
      title: 'Cloud Computing',
      credits: 3,
      prerequisites: ['cse309'],
      group: G.a04,
    },
    {
      id: 'cse476',
      code: 'CSE 476',
      title: 'Bayesian Data Analysis',
      credits: 3,
      prerequisites: ['cse317', 'cse317l', 'mat212', 'cse425'],
      group: G.a04,
    },
    {
      id: 'cse477',
      code: 'CSE 477',
      title: 'Data Science for Sustainable Development',
      credits: 3,
      prerequisites: ['cse432'],
      group: G.a04,
    },
    {
      id: 'cse478',
      code: 'CSE 478',
      title: 'Business Analytics: Data Analysis and Decision Making',
      credits: 3,
      prerequisites: ['cse432'],
      group: G.a04,
    },

    // ── Area 05 — Intelligent Systems ────────────────────────────────
    {
      id: 'cse420',
      code: 'CSE 420',
      title: 'Image Processing',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a05,
    },
    {
      id: 'cse423',
      code: 'CSE 423',
      title: 'Theory of Fuzzy Systems',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a05,
    },
    {
      id: 'cse424',
      code: 'CSE 424',
      title: 'Neural Networks',
      credits: 3,
      prerequisites: ['cse425', 'cse417'],
      group: G.a05,
    },
    {
      id: 'cse426',
      code: 'CSE 426',
      title: 'Introduction to Robotics',
      credits: 3,
      prerequisites: ['cse425'],
      group: G.a05,
    },
    {
      id: 'cse428',
      code: 'CSE 428',
      title: 'Computer Vision',
      credits: 3,
      prerequisites: ['cse424'],
      group: G.a05,
    },
    {
      id: 'cse473',
      code: 'CSE 473',
      title: 'Natural Language Processing',
      credits: 3,
      prerequisites: ['cse424', 'cse417'],
      group: G.a05,
    },
    {
      id: 'cse479',
      code: 'CSE 479',
      title: 'Introduction to Reinforcement Learning',
      credits: 3,
      prerequisites: ['cse424'],
      group: G.a05,
    },
    {
      id: 'cse470',
      code: 'CSE 470',
      title: 'Introduction to Graphical Models',
      credits: 3,
      prerequisites: ['cse421'],
      group: G.a05,
    },

    // ── Area 06A — Information Systems & Processing ───────────────────
    {
      id: 'cse413',
      code: 'CSE 413',
      title: 'Advanced Database Management Systems',
      credits: 3,
      prerequisites: ['cse303', 'cse303l', 'cse309'],
      group: G.a06a,
    },
    {
      id: 'cse414',
      code: 'CSE 414',
      title: 'Database Systems Implementation',
      credits: 3,
      prerequisites: ['cse303', 'cse303l'],
      group: G.a06a,
    },
    {
      id: 'cse416',
      code: 'CSE 416',
      title: 'Distributed Database Systems',
      credits: 3,
      prerequisites: ['cse303', 'cse303l'],
      group: G.a06a,
    },
    {
      id: 'cse418',
      code: 'CSE 418',
      title: 'E-commerce and Web Database',
      credits: 3,
      prerequisites: ['cse309'],
      group: G.a06a,
    },
    {
      id: 'cse436',
      code: 'CSE 436',
      title: 'Multimedia Systems',
      credits: 3,
      prerequisites: ['cse438'],
      group: G.a06a,
    },

    // ── Area 06B — Information Systems & Processing ───────────────────
    {
      id: 'cse433',
      code: 'CSE 433',
      title: 'Introduction to Parallel Programming',
      credits: 3,
      prerequisites: ['cse213', 'cse213l'],
      group: G.a06b,
    },
    {
      id: 'cse471',
      code: 'CSE 471',
      title: 'Introduction to High Performance Computing',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a06b,
    },
    {
      id: 'cse486',
      code: 'CSE 486',
      title: 'Advanced Cloud Computing',
      credits: 3,
      prerequisites: ['cse472'],
      group: G.a06b,
    },

    // ── Area 07 — CS Theory ───────────────────────────────────────────
    {
      id: 'cse301',
      code: 'CSE 301',
      title: 'Finite Automata and Computability',
      credits: 3,
      prerequisites: ['cse211', 'cse211l'],
      group: G.a07,
    },
    {
      id: 'cse313',
      code: 'CSE 313',
      title: 'Compiler Construction',
      credits: 3,
      prerequisites: ['cse301'],
      group: G.a07,
    },
    {
      id: 'cse429',
      code: 'CSE 429',
      title: 'Introduction to Operations Research',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a07,
    },
    {
      id: 'cse435',
      code: 'CSE 435',
      title: 'Computer Graphics',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a07,
    },
    {
      id: 'cse480',
      code: 'CSE 480',
      title: 'Topics in Theoretical Computer Science',
      credits: 3,
      prerequisites: ['cse301'],
      group: G.a07,
    },
    {
      id: 'cse481',
      code: 'CSE 481',
      title: 'Algorithm in the Real World',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a07,
    },
    {
      id: 'cse482',
      code: 'CSE 482',
      title: 'Introduction to Quantum Computing',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a07,
    },
    {
      id: 'cse483',
      code: 'CSE 483',
      title: 'Introduction to Cryptography',
      credits: 3,
      prerequisites: ['cse211', 'cse211l', 'cse316', 'cse316l'],
      group: G.a07,
    },
    {
      id: 'cse484',
      code: 'CSE 484',
      title: 'Introduction to Complex Network Analysis',
      credits: 3,
      prerequisites: ['cse424'],
      group: G.a07,
    },
    {
      id: 'cse485',
      code: 'CSE 485',
      title: 'Introduction to Game Theory & Mechanism Design',
      credits: 3,
      prerequisites: ['cse425'],
      group: G.a07,
    },
    {
      id: 'mat401',
      code: 'MAT 401',
      title: 'Graph Theory',
      credits: 3,
      prerequisites: ['cse211', 'cse211l'],
      group: G.a07,
    },
    {
      id: 'mat420',
      code: 'MAT 420',
      title: 'Computational Geometry',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a07,
    },

    // ── Area 08 — Scientific Computing ───────────────────────────────
    {
      id: 'cse427',
      code: 'CSE 427',
      title: 'Computer Simulation and Modeling',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a08,
    },
    {
      id: 'mat405',
      code: 'MAT 405',
      title: 'Optimization Techniques',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a08,
    },
    {
      id: 'mat430',
      code: 'MAT 430',
      title: 'Differential Equations and Dynamical Systems',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a08,
    },
    {
      id: 'cse474',
      code: 'CSE 474',
      title: 'Introduction to Bioinformatics',
      credits: 3,
      prerequisites: ['cse211', 'cse211l'],
      group: G.a08,
    },
    {
      id: 'cse475',
      code: 'CSE 475',
      title: 'Introduction to Astro-informatics',
      credits: 3,
      prerequisites: ['cse211', 'cse211l', 'phy102'],
      group: G.a08,
    },
    {
      id: 'mat403',
      code: 'MAT 403',
      title: 'Introduction to Mathematical Modeling',
      credits: 3,
      prerequisites: ['cse317', 'cse317l'],
      group: G.a08,
    },

    // ── Area 09 — Data Analytics & Digitalization ─────────────────────
    {
      id: 'cse488',
      code: 'CSE 488',
      title: 'Introduction to Data Visualization, Statistical Modeling and ML',
      credits: 3,
      prerequisites: ['cse432'],
      group: G.a09,
    },
    {
      id: 'cse489',
      code: 'CSE 489',
      title: 'Advanced Statistical Modeling, ML and Deep Learning',
      credits: 3,
      prerequisites: ['cse432'],
      group: G.a09,
    },

    // ── Area 10 — Information Technology ─────────────────────────────
    {
      id: 'cse431',
      code: 'CSE 431',
      title: 'Advanced Object Oriented Programming',
      credits: 3,
      prerequisites: ['cse213', 'cse213l'],
      group: G.a10,
    },
    {
      id: 'cse434',
      code: 'CSE 434',
      title: 'Advance Programming in UNIX',
      credits: 3,
      prerequisites: ['cse315'],
      group: G.a10,
    },
    {
      id: 'cse463',
      code: 'CSE 463',
      title: 'IT Security',
      credits: 3,
      prerequisites: ['cse316', 'cse316l'],
      group: G.a10,
    },
    {
      id: 'cse464',
      code: 'CSE 464',
      title: 'Mobile Application Development',
      credits: 3,
      prerequisites: ['cse213', 'cse213l'],
      group: G.a10,
    },
    {
      id: 'cse465',
      code: 'CSE 465',
      title: 'Advanced Web Programming',
      credits: 3,
      prerequisites: ['cse309'],
      group: G.a10,
    },
    {
      id: 'cse466',
      code: 'CSE 466',
      title: 'Human Computer Interaction',
      credits: 3,
      prerequisites: ['cse213', 'cse213l'],
      group: G.a10,
    },
    {
      id: 'cse499',
      code: 'CSE 499',
      title: 'Internship Program',
      credits: 3,
      prerequisites: [],
      group: G.a10,
    },

    // ── Special Topics ────────────────────────────────────────────────
    {
      id: 'cse490',
      code: 'CSE 490',
      title: 'Special Topics in CSE',
      credits: 3,
      prerequisites: [],
      group: G.special,
    },
  ],
};
