export { HeroSection } from './hero-section';
export { QuickFacts } from './quick-facts';
export { HighlightsSection } from './highlights-section';
export { ResearchPhilosophy } from './research-philosophy';
export { SkillsSection } from './skills-section';
export { BeyondAcademia } from './beyond-academia';
export { CertificationsSection } from './certifications-section';
export { AwardsSection } from './awards-section';
export { CtaSection } from './cta-section';
