export * from './hero-section';
export * from './quick-facts';
export * from './highlights-section';
export * from './research-philosophy';
export * from './skills-section';
export * from './beyond-academia';
export * from './certifications-section';
export * from './awards-section';
export * from './cta-section';
